### PR TITLE
punctuation legal in metatext titles

### PR DESCRIPTION
**Pull request by WardCunningham**
This changes a regular expression to allow creating pages with punctuation in their titles.

This example uses a hyphen in the title of one page.

image

This also has my docker stuff as I am unsure how to build the images I need within the github automation without first exposing this project as something accessible from there, like a docker image. (I'd rather just launch deno with seran-wiki as an import from a public address, then I can stop using docker to distribute it.

### CODE REVIEW

**Comment by joshuabenuck** [comment]
Merging docker support seems like a reasonable workaround until we can just install using deno. I'll research what our options are to get there.

**Comment by joshuabenuck** [comment]
I had to change the username used in the workflow file for the action to succeed. Not sure if you'll need to update anything on your end.

**Comment by joshuabenuck** [comment]
Do github actions inject a variable that abstracts the username or the repo path? That would allow the actions file to work without changes on forks.

**Comment by WardCunningham** [comment]
Thanks for including this.

Pat tried to write a parameterized action but it didn't work and it was getting late.

**Pull request merged**
