### PR TITLE
experiment with static pages in code

### PR DESCRIPTION
**Pull request by WardCunningham**
see `http://metatext.localtest.me:8000/index.html` for static pages in code.

image

This might be an approach for including navigation and documentation in a meta-site.

(I almost got the arbitrary type item generator working but had to call it a night.)

### CODE REVIEW

**Comment by joshuabenuck** [comment]
Interesting.

I created `static.localhost.ts` partially as a way to create a more fully functioning wiki client and partially as a way to build up the logic that could go into a static page api in `site`. My thought was that the latter could be useful for the same use case as your metatext experiment. The downside of the static page approach is that it makes it harder to have a single file meta-site.

I like the direction this is going in.

Do you want this merged now or would you prefer I wait until your item generator is working?

**Comment by WardCunningham** [comment]
I see no long term value in this being merged as it doesn't offer value as a meta-site. I was thinking if this worked well enough it could become an important part of `site` in whatever it becomes.

I don't have much experience with a downstream repo. I'm not using branches so this might have to merge if I am to continue working this way and still contribute other code by pull request. The question becomes one of workflows when building on rapidly evolving foundations. We will discuss.

**Comment by WardCunningham** [comment]
It occurs to me that a string literal page format could interpolate results using the ${ ... } notation. For example, to create a type=data item I might write:
```
site.metatext(`
Results
  We get these results. View with [[Radar Chart]].

  data:
    columns: ${Object.keys(result[0]}
    data: ${results}
`)
```
Aside: see an example of the data plugin in use here: [wiki](http://best.ward.bay.wiki.org/making-best-cities-site.html), [json](http://best.ward.bay.wiki.org/making-best-cities-site.json)

**Comment by joshuabenuck** [comment]
Good point! That quickly becomes quite powerful.

**Comment by WardCunningham** [comment]
Oops. I didn't see you've added params to init. I'll see if I can find where this is used and update it to the options hash I'm using, unless you have a better suggestion.

image

**Comment by WardCunningham** [comment]
I'm not sure how to test this change but it looks pretty hard to get wrong.

**Comment by joshuabenuck** [comment]
Looks good. I'm not exactly sure how to manually test changes before merging. That's a workflow I'm going to have to learn soon.

I'm okay with merging this if you are ready for it to be merged.

**Comment by WardCunningham** [comment]
Merge away.

**Pull request merged**
