### PR TITLE
add allow-run permission

### PR DESCRIPTION
**Pull request by WardCunningham**
I'm happy to confer these privileges some other way but for now I need this for my DiG PNG generator.

### CODE REVIEW

**Comment by joshuabenuck** [comment]
Two changes needed:
* Remove the github workflow changes from the PR
* Add the `--allow-run` flag to `seran-wiki.cmd`

**Comment by WardCunningham** [comment]
@pcunning was exploring ways to parameterize the build actions such that we need not stay exactly in sync but could merge without conflict. I will see if we can't get that to work over the weekend. Happy to hold off on this merge until then.

**Comment by WardCunningham** [comment]
Note: The actions have to be right when I push because that is what triggers my docker image build.

**Comment by joshuabenuck** [comment]
I merged in Eric's changes which enables this to be merged.

**Pull request merged**
